{{- if .Values.netPol.enabled }}
{{- range $index, $value := .Values.netPol.policies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  ingress:
    {{- if .ingressEnabled }}
      {{- toYaml .ingress | nindent 4 }}
    {{- end }}
  egress:
    {{- if .egressEnabled }}
      {{- toYaml .egress | nindent 4 }}
    {{- end }}
  policyTypes: {{ toYaml .policyTypes | nindent 4 }}  
  podSelector: {{ toYaml .podSelector | nindent 4 }}
  ---
  {{- end }}
  {{- end }}
 