{{- if .Values.netPol.enabled }}
{{- range $index, $value := .Values.netPol.policies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  {{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}  
  {{- end }}
  {{- if .labels }}
  labels:
    {{- toYaml .labels | nindent 4 }}  
  {{- end }}
spec:
  {{- if has "Ingress" .policyTypes }}
  ingress:
    {{- toYaml .ingress | nindent 4 }}
  {{- end }}
  {{- if has "Egress" .policyTypes }}  
  egress:
    {{- toYaml .egress | nindent 4 }}
  {{- end }}
  policyTypes: 
    {{- toYaml .policyTypes | nindent 4 }}  
  podSelector: 
    {{- toYaml .podSelector | nindent 4 }}
---
{{- end }}
{{- end }}
